<?php

namespace Modules\Flight\Controllers;

use App\Http\Controllers\Controller;


use App\Models\SearchSession;
//use App\Service\SabreApiService;
use App\Service\SabreApiService;
use Modules\Flight\Admin\FlightFilterTrait;
use Modules\Flight\Admin\SabreDataProcessorTrait;
use Modules\Flight\Models\FlightDiscount;
use Modules\Flight\Models\SeatType;
use Modules\Flight\Models\Airport;
use Modules\Flight\Service\FlightSearchService;
use Modules\Flight\Service\PassengerProcessor;
use Modules\Flight\Service\SegmentProcessor;
use Modules\Flight\Service\SabreFlightService;
use Modules\Location\Models\LocationCategory;
use Modules\Flight\Models\Flight;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use DB;
use Illuminate\Support\Facades\Log;

class FlightController extends Controller
{
//    use SabreDataProcessorTrait, FlightFilterTrait;
    protected $flightClass;
    protected $locationClass;
    protected $segmentProcessor;
    protected $passengerProcessor;
    protected $sabreApiService;
    protected $flightSearch;
    private $locationCategoryClass;



    public function __construct(Flight $flightClass,
                                Location $locationClass,
                                SegmentProcessor $segmentProcessor,
                                PassengerProcessor $passengerProcessor,
                                FlightSearchService $flightSearch,
                                )
    {
        $this->flightClass = $flightClass;
        $this->locationClass = $locationClass;
        $this->segmentProcessor = $segmentProcessor;
        $this->passengerProcessor = $passengerProcessor;
        $this->flightSearch = $flightSearch;
    }

    public function callAction($method, $parameters)
    {
        if (!Flight::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

//    =====================================
    // ============================================
    // MAIN SEARCH METHOD (SIMPLIFIED)
    // ============================================

    public function index(Request $request)
    {
        $reissueParams = session('reissue_search_params');

        if ($reissueParams) {
            $validated = $reissueParams;
            session()->forget('reissue_search_params');
            Log::info('🔄 Reissue Flight Search', [
                'reissue_id' => $validated['reissue_id'] ?? null,
                'booking_id' => $validated['booking_id'] ?? null
            ]);
        } else {
            $validated = $request->validate([
                'trip_type'       => 'required|in:oneway,round,multi',
                'segments'        => 'required|array|min:1',
                'segments.*.from' => 'required',
                'segments.*.to'   => 'required',
                'segments.*.departure' => 'required|date',
                'return_date'     => 'nullable|date',
                'adults'          => 'required|integer|min:1|max:9',
                'children'        => 'nullable|integer|min:0',
                'infants'         => 'nullable|integer|min:0',
                'children_ages'   => 'nullable|array',
                'children_ages.*' => 'integer|min:0|max:12',
                'travel_class'    => 'required|in:ECONOMY,BUSINESS,FIRST',
                'airline_codes'   => 'nullable',
            ]);

            $passengerErrors = $this->passengerProcessor->validatePassengers($validated);
            if (!empty($passengerErrors)) {
                if ($request->expectsJson() || $request->ajax()) {
                    return response()->json(['errors' => $passengerErrors], 422);
                }
                return redirect()->back()->withErrors($passengerErrors)->withInput();
            }

            $tripValidationErrors = $this->segmentProcessor->validateRoundTrip(
                $validated['trip_type'],
                $validated['return_date'] ?? '',
                $validated['segments']
            );
            if (!empty($tripValidationErrors)) {
                if ($request->expectsJson() || $request->ajax()) {
                    return response()->json(['errors' => $tripValidationErrors], 422);
                }
                return redirect()->back()->withErrors($tripValidationErrors)->withInput();
            }
        }

        // ✅ Streaming response
        if ($request->expectsJson() || $request->ajax()) {
            session(['flight_search_params' => $validated]);
            return response()->stream(function () use ($validated) {
                

                $this->flightSearch->searchStream($validated, function ($flight) {
                    echo "data: " . json_encode($flight) . "\n\n";
                    ob_flush();
                    flush();
                });

                echo "data: [DONE]\n\n";
                ob_flush();
                flush();

            }, 200, [
                'Content-Type'      => 'text/event-stream',
                'Cache-Control'     => 'no-cache',
                'X-Accel-Buffering' => 'no',
            ]);
        }

        // ✅ Normal page load — frontend streaming করবে
        session(['flight_search_params' => $validated]);

        return view('Flight::frontend.vueSearch.flight_search', [
            'flights'      => [],
            'searchParams' => $validated,
        ]);
    }

    public function getData(Request $request, $id)
    {
        $row = $this->flightClass::with(['flightSeat.seatType', 'airportFrom', 'airportTo', 'airline', 'bookingPassengers'])->find($id);
        if (empty($row)) {
            return $this->sendError('no found');
        } else {
            if (!empty($row->airline)) {
                $row->airline->append(['image_url']);
            }
            $bookingPassengers = $row->bookingPassengers->countBy('seat_type')->toArray();
            if (!empty($row->flightSeat)) {
                foreach ($row->flightSeat as &$value) {
                    if (!empty($bookingPassengers[$value->seat_type])) {
                        $value->max_passengers = $value->max_passengers - $bookingPassengers[$value->seat_type];
                        if ($value->max_passengers < 0) {
                            $value->max_passengers = 0;
                        }
                    }
                    $value->price_html = format_money($value->price);
                    $value->number = 0;
                }
            }
            $row->departure_time_html = $row->departure_time->format('H:i');
            $row->departure_date_html = $row->departure_time->format('D, d M y');
            $row->arrival_time_html = $row->arrival_time->format('H:i');
            $row->arrival_date_html = $row->arrival_time->format('D, d M y');

            return $this->sendSuccess(['data' => $row->toArray()], 'founded');
        }
    }

    /**
     * Helper method to get airline image URL
     */
    private function getAirlineImage($airlineCode)
    {
        try {
            $airline = \Modules\Flight\Models\Airline::where('designator', $airlineCode)->first();
            if ($airline && $airline->image_id) {
                return get_file_url($airline->image_id, 'thumb', true);
            }
        } catch (\Exception $e) {
            // Log error if needed
        }
        return ''; // Return empty string if no image found
    }

    /**
     * Get all airports for multi-city segments
     */
    private function getSegmentAirports(Request $request)
    {
        $segments = $request->input('segments', []);
        $segmentAirports = [];

        foreach ($segments as $index => $segment) {
            $fromId = $segment['from'] ?? null;
            $toId = $segment['to'] ?? null;

            $segmentAirports[$index] = [
                'from' => $fromId ? Airport::find($fromId) : null,
                'to' => $toId ? Airport::find($toId) : null,
            ];
        }

        return $segmentAirports;
    }

    /**
     * Apply backend filters to flight results
     */

    private function applyBackendFilters($flights, Request $request)
    {
        if (empty($flights)) {
            return $flights;
        }

        $filtered = $flights;
//return $request;
        // 1. Price Range Filter
        if ($request->has('price_range')) {
            $priceRange = explode(';', $request->input('price_range'));
            if (count($priceRange) == 2) {
                $minPrice = (float)$priceRange[0];
                $maxPrice = (float)$priceRange[1];

                $filtered = array_filter($filtered, function ($flight) use ($minPrice, $maxPrice) {
                    $price = $flight['price'] ?? 0;
                    return $price >= $minPrice && $price <= $maxPrice;
                });
            }
        }

        // 2. Airline Code Filter
        if ($request->has('airline_codes') && is_array($request->input('airline_codes'))) {
            $selectedAirlineCodes = $request->input('airline_codes');

            $filtered = array_filter($filtered, function ($flight) use ($selectedAirlineCodes) {
                $airlineCode = $flight['airline_code'] ?? '';
                return in_array($airlineCode, $selectedAirlineCodes);
            });
        }

        // 3. ✅ Stops Filter (FIXED)
        if ($request->has('stop_type') && !empty($request->input('stop_type'))) {
            $stopType = $request->input('stop_type');

            $filtered = array_filter($filtered, function ($flight) use ($stopType) {
                // Get first itinerary segments
                $originalData = $flight['original_data'] ?? null;
                if (!$originalData || !isset($originalData->itineraries)) {
                    return false;
                }

                $itineraries = $originalData->itineraries;
                if (empty($itineraries)) return false;

                // Get first leg segments
                $firstItinerary = is_object($itineraries[0]) ? $itineraries[0] : (object)$itineraries[0];
                $segments = $firstItinerary->segments ?? [];

                // Convert to array if needed
                if (is_object($segments)) {
                    $segments = (array)$segments;
                }

                $stopsCount = max(count($segments) - 1, 0);

                // Match stop type
                switch ($stopType) {
                    case 'non-stop':
                        return $stopsCount === 0;
                    case 'one-stop':
                        return $stopsCount === 1;
                    case 'two-stop':
                        return $stopsCount >= 2;
                    default:
                        return true;
                }
            });
        }

        // 4. ✅ Refund Type Filter (FIXED)
//        if ($request->has('refund_type') && !empty($request->input('refund_type'))) {
//            $refundType = $request->input('refund_type');
//
//            $filtered = array_filter($filtered, function ($flight) use ($refundType) {
//                // Get refund status from Sabre data structure
//                $originalData = $flight['original_data'] ?? null;
//                if (!$originalData) {
//                    // Default: non-refundable
//                    $isRefundable = false;
//                } else {
//                    // Check passengerInfoList -> passengerInfo -> nonRefundable
//                    $passengerInfoList = $originalData->passengerInfoList ?? [];
//
//                    if (!empty($passengerInfoList) && isset($passengerInfoList[0]->passengerInfo)) {
//                        $passengerInfo = $passengerInfoList[0]->passengerInfo;
//
//                        // nonRefundable = true means NOT refundable
//                        // nonRefundable = false means refundable
//                        $nonRefundable = $passengerInfo->nonRefundable ?? true;
//                        $isRefundable = !$nonRefundable; // Invert the flag
//                    } else {
//                        // Default: non-refundable if not specified
//                        $isRefundable = false;
//                    }
//                }
//
//                // Filter by type
//                if ($refundType === 'refundable') {
//                    return $isRefundable === true;
//                } elseif ($refundType === 'non-refundable') {
//                    return $isRefundable === false;
//                }
//
//                return true; // 'all' or empty
//            });
//        }

        // 4. ✅ Refund Type Filter
        // 4. ✅ Refund Type Filter
        if ($request->has('refund_type') && !empty($request->input('refund_type'))) {
            $refundType = $request->input('refund_type');

            $filtered = array_filter($filtered, function ($flight) use ($refundType) {
                $isRefundable = false;
                $originalData = $flight['original_data'] ?? null;

                if ($originalData) {
                    // ✅ Both array and object support
                    $passengerInfoList = is_object($originalData)
                        ? ($originalData->passengerInfoList ?? [])
                        : ($originalData['passengerInfoList'] ?? []);

                    if (!empty($passengerInfoList)) {
                        $firstItem = is_array($passengerInfoList) ? $passengerInfoList[0] : $passengerInfoList[0];

                        // ✅ Check both array and object notation
                        if (is_array($firstItem)) {
                            // Array format: ['passengerInfo']['nonRefundable']
                            $nonRefundable = $firstItem['passengerInfo']['nonRefundable'] ?? true;
                            $isRefundable = !$nonRefundable;
                        } elseif (is_object($firstItem) && isset($firstItem->passengerInfo)) {
                            // Object format: ->passengerInfo->nonRefundable
                            $nonRefundable = $firstItem->passengerInfo->nonRefundable ?? true;
                            $isRefundable = !$nonRefundable;
                        } elseif (is_object($firstItem) && isset($firstItem->nonRefundable)) {
                            // Direct format: ->nonRefundable
                            $isRefundable = !$firstItem->nonRefundable;
                        }
                    }
                }

                // Apply filter
                if ($refundType === 'refundable') {
                    return $isRefundable === true;
                } elseif ($refundType === 'non-refundable') {
                    return $isRefundable === false;
                }

                return true;
            });
        }

        // 5. ✅ Time Slots Filter (FIXED)
//        if ($request->has('time_slots') && !empty($request->input('time_slots'))) {
//            $selectedSlots = explode(',', $request->input('time_slots'));
//
//            $filtered = array_filter($filtered, function ($flight) use ($selectedSlots) {
//                // Get departure time from original_data
//                $originalData = $flight['original_data'] ?? null;
//                if (!$originalData || !isset($originalData->itineraries)) {
//                    return false;
//                }
//
//                $itineraries = $originalData->itineraries;
//                if (empty($itineraries)) return false;
//
//                // Get first segment departure time
//                $firstItinerary = is_object($itineraries[0]) ? $itineraries[0] : (object)$itineraries[0];
//                $segments = $firstItinerary->segments ?? [];
//
//                if (empty($segments)) return false;
//
//                $firstSegment = is_object($segments[0]) ? $segments[0] : (object)$segments[0];
//                $departureAt = $firstSegment->departure->at ?? '';
//
//                if (empty($departureAt)) return false;
//
//                // Parse time from ISO format with timezone
//                // Example: "2025-12-15T17:00:00+06:00"
//                try {
//                    $dateTime = new \DateTime($departureAt);
//                    $hour = (int)$dateTime->format('H'); // Get hour (0-23)
//                } catch (\Exception $e) {
//                    return false;
//                }
//
//                // Check which slot this flight belongs to
//                foreach ($selectedSlots as $slot) {
//                    $slotParts = explode('-', trim($slot));
//                    if (count($slotParts) !== 2) continue;
//
//                    $start = (int)$slotParts[0];
//                    $end = (int)$slotParts[1];
//
//                    // Handle midnight wrap-around (18-00 means 18-24)
//                    if ($end == 0) {
//                        $end = 24;
//                    }
//
//                    // Check if hour falls in this slot
//                    if ($hour >= $start && $hour < $end) {
//                        return true;
//                    }
//                }
//
//                return false;
//            });
//        }


        if ($request->has('time_slots') && !empty($request->input('time_slots'))) {
            $timeSlots = $request->input('time_slots');

            // ✅ Handle both array and comma-separated string
            $selectedSlots = is_array($timeSlots) ? $timeSlots : explode(',', $timeSlots);

            $filtered = array_filter($filtered, function ($flight) use ($selectedSlots) {
                $originalData = $flight['original_data'] ?? null;

                // ✅ Handle both object and array
                if (!$originalData) return false;

                $itineraries = is_object($originalData)
                    ? ($originalData->itineraries ?? null)
                    : ($originalData['itineraries'] ?? null);

                if (empty($itineraries)) return false;

                // Get first segment departure time
                $firstItinerary = is_array($itineraries[0])
                    ? $itineraries[0]
                    : (array)$itineraries[0];

                $segments = $firstItinerary['segments'] ?? ($firstItinerary->segments ?? []);
                if (empty($segments)) return false;

                $firstSegment = is_array($segments[0])
                    ? $segments[0]
                    : (array)$segments[0];

                $departureAt = $firstSegment['departure']['at']
                    ?? ($firstSegment['departure']->at ?? null);

                if (empty($departureAt)) return false;

                // Parse time from ISO format
                try {
                    $dateTime = new \DateTime($departureAt);
                    $hour = (int)$dateTime->format('H'); // 0-23
                } catch (\Exception $e) {
                    return false;
                }

                // Check if hour falls in any selected slot
                foreach ($selectedSlots as $slot) {
                    $slotParts = explode('-', trim($slot));
                    if (count($slotParts) !== 2) continue;

                    $start = (int)$slotParts[0];
                    $end = (int)$slotParts[1];

                    // Handle midnight wrap-around (18-00 means 18-24)
                    if ($end == 0) $end = 24;

                    // ✅ Check if hour falls in this slot
                    if ($hour >= $start && $hour < $end) {
                        return true;
                    }
                }

                return false;
            });
        }

        // 6. Airline Filter (from attrs) - Legacy support
        if ($request->has('attrs') && is_array($request->input('attrs'))) {
            $attrs = $request->input('attrs');

            if (isset($attrs['airlines']) && is_array($attrs['airlines'])) {
                $selectedAirlines = $attrs['airlines'];

                $filtered = array_filter($filtered, function ($flight) use ($selectedAirlines) {
                    $airlineCode = $flight['airline_code'] ?? '';

                    $airlineName = '';
                    try {
                        $airlineName = airline_from_code($airlineCode);
                    } catch (\Exception $e) {
                        $airlineName = $airlineCode;
                    }

                    foreach ($selectedAirlines as $selectedAirline) {
                        if (
                            stripos($airlineName, $selectedAirline) !== false ||
                            stripos($selectedAirline, $airlineName) !== false ||
                            stripos($airlineCode, $selectedAirline) !== false ||
                            stripos($selectedAirline, $airlineCode) !== false
                        ) {
                            return true;
                        }
                    }

                    return false;
                });
            }

            if (isset($attrs['stopes']) && is_array($attrs['stopes'])) {
                $selectedStops = $attrs['stopes'];

                $filtered = array_filter($filtered, function ($flight) use ($selectedStops) {
                    $originalData = $flight['original_data'] ?? null;
                    if (!$originalData || !isset($originalData->itineraries)) {
                        return false;
                    }

                    $itineraries = $originalData->itineraries;
                    if (empty($itineraries)) return false;

                    $firstItinerary = is_object($itineraries[0]) ? $itineraries[0] : (object)$itineraries[0];
                    $segments = $firstItinerary->segments ?? [];

                    if (is_object($segments)) {
                        $segments = (array)$segments;
                    }

                    $stops = max(count($segments) - 1, 0);

                    $stopKey = match (true) {
                        $stops === 0 => 'non-stop',
                        $stops === 1 => 'one-stop',
                        $stops >= 2 => 'one-plus',
                    };

                    return in_array($stopKey, $selectedStops);
                });
            }
        }

        // 7. Duration Filter
        if ($request->has('max_duration')) {
            $maxDuration = (int)$request->input('max_duration');

            $filtered = array_filter($filtered, function ($flight) use ($maxDuration) {
                $duration = $flight['duration'] ?? '';
                $durationMinutes = $this->parseDurationToMinutes($duration);
                return $durationMinutes <= $maxDuration;
            });
        }

        // 8. Sorting
        if ($request->has('orderby')) {
            $orderby = $request->input('orderby');

            usort($filtered, function ($a, $b) use ($orderby) {
                switch ($orderby) {
                    case 'price_low_high':
                        return ($a['price'] ?? 0) <=> ($b['price'] ?? 0);

                    case 'price_high_low':
                        return ($b['price'] ?? 0) <=> ($a['price'] ?? 0);

                    case 'duration_low_high':
                        $aDuration = $this->parseDurationToMinutes($a['duration'] ?? '');
                        $bDuration = $this->parseDurationToMinutes($b['duration'] ?? '');
                        return $aDuration <=> $bDuration;

                    case 'duration_high_low':
                        $aDuration = $this->parseDurationToMinutes($a['duration'] ?? '');
                        $bDuration = $this->parseDurationToMinutes($b['duration'] ?? '');
                        return $bDuration <=> $aDuration;

                    default:
                        return 0;
                }
            });
        }

        return array_values($filtered);
    }
//    private function applyBackendFilters($flights, Request $request)
//    {
//        if (empty($flights)) {
//            return $flights;
//        }
//
//        $filtered = $flights;
//
//        // 1. Price Range Filter
//        if ($request->has('price_range')) {
//            $priceRange = explode(';', $request->input('price_range'));
//            if (count($priceRange) == 2) {
//                $minPrice = (float)$priceRange[0];
//                $maxPrice = (float)$priceRange[1];
//
//                $filtered = array_filter($filtered, function ($flight) use ($minPrice, $maxPrice) {
//                    $price = $flight['price'] ?? 0;
//                    return $price >= $minPrice && $price <= $maxPrice;
//                });
//            }
//        }
//        // 10. Time Slots Filter
//        if ($request->has('time_slots') && !empty($request->input('time_slots'))) {
//            $selectedSlots = explode(',', $request->input('time_slots'));
//
//            $filtered = array_filter($filtered, function ($flight) use ($selectedSlots) {
//                $departureTime = $flight['departure_time'] ?? '';
//
//                if (empty($departureTime)) return false;
//
//                // Extract hour from datetime (2025-12-15T08:30:00)
//                $hour = (int)date('H', strtotime($departureTime));
//
//                // Check which slot this flight belongs to
//                foreach ($selectedSlots as $slot) {
//                    list($start, $end) = explode('-', $slot);
//                    $start = (int)$start;
//                    $end = (int)$end;
//
//                    // Handle midnight wrap-around
//                    if ($end == 0) $end = 24;
//
//                    if ($hour >= $start && $hour < $end) {
//                        return true;
//                    }
//                }
//
//                return false;
//            });
//        }
//
//        // 2. Airline Filter (from attrs)
//        if ($request->has('attrs') && is_array($request->input('attrs'))) {
//            $attrs = $request->input('attrs');
//
//            // Airlines filter
//            if (isset($attrs['airlines']) && is_array($attrs['airlines'])) {
//                $selectedAirlines = $attrs['airlines'];
//
//                $filtered = array_filter($filtered, function ($flight) use ($selectedAirlines) {
//                    $airlineCode = $flight['airline_code'] ?? '';
//
//                    // Get airline name from code
//                    $airlineName = '';
//                    try {
//                        $airlineName = airline_from_code($airlineCode);
//                    } catch (\Exception $e) {
//                        $airlineName = $airlineCode;
//                    }
//
//                    // Check if matches any selected airline
//                    foreach ($selectedAirlines as $selectedAirline) {
//                        // Match by name or code
//                        if (
//                            stripos($airlineName, $selectedAirline) !== false ||
//                            stripos($selectedAirline, $airlineName) !== false ||
//                            stripos($airlineCode, $selectedAirline) !== false ||
//                            stripos($selectedAirline, $airlineCode) !== false
//                        ) {
//                            return true;
//                        }
//                    }
//
//                    return false;
//                });
//            }
//
//            // Other attrs filters (cabin class, etc.)
//            foreach ($attrs as $attrKey => $attrValues) {
//                if ($attrKey === 'airlines' || !is_array($attrValues)) {
//                    continue;
//                }
//
//                $filtered = array_filter($filtered, function ($flight) use ($attrKey, $attrValues) {
//                    // Add custom logic for other attributes here
//                    // Example: cabin class, baggage, etc.
//                    return true; // Keep all for now
//                });
//            }
//        }
//
//        // 2a. Airline Code Filter (direct from airline_codes[])
//        if ($request->has('airline_codes') && is_array($request->input('airline_codes'))) {
//            $selectedAirlineCodes = $request->input('airline_codes');
//
//            $filtered = array_filter($filtered, function ($flight) use ($selectedAirlineCodes) {
//                $airlineCode = $flight['airline_code'] ?? '';
//                return in_array($airlineCode, $selectedAirlineCodes);
//            });
//        }
//
//        // 3. Stops Filter (Corrected)
//        // Stops Filter via attrs
//        if (isset($attrs['stopes']) && is_array($attrs['stopes'])) {
//
//            $selectedStops = $attrs['stopes']; // Example: ['non-stop', 'one-stop']
//
//            $filtered = array_filter($filtered, function ($flight) use ($selectedStops) {
//
//                // Get segments count (safe cast)
//                $itineraries = $flight['itineraries'] ?? [];
//                if (empty($itineraries)) return false;
//
//                $first = $itineraries[0];
//                $segments = $first->segments ?? $first['segments'] ?? [];
//                $stops = max(count($segments) - 1, 0);
//
//                // Convert stops count → keyword
//                $stopKey = match (true) {
//                    $stops === 0 => 'non-stop',
//                    $stops === 1 => 'one-stop',
//                    $stops >= 2 => 'one-plus',
//                };
//
//                // Check if selected
//                return in_array($stopKey, $selectedStops);
//            });
//        }
//
//
//        // 4. Departure Time Filter
//        if ($request->has('departure_time')) {
//            $departureTime = $request->input('departure_time');
//
//            $filtered = array_filter($filtered, function ($flight) use ($departureTime) {
//                $flightDepartureTime = $flight['departure_time'] ?? '';
//                return $this->matchesTimeRange($flightDepartureTime, $departureTime);
//            });
//        }
//
//        // 5. Arrival Time Filter
//        if ($request->has('arrival_time')) {
//            $arrivalTime = $request->input('arrival_time');
//
//            $filtered = array_filter($filtered, function ($flight) use ($arrivalTime) {
//                $flightArrivalTime = $flight['arrival_time'] ?? '';
//                return $this->matchesTimeRange($flightArrivalTime, $arrivalTime);
//            });
//        }
//
//        // 6. Cabin Class Filter
//        if ($request->has('cabin_class')) {
//            $cabinClass = strtoupper($request->input('cabin_class'));
//
//            $filtered = array_filter($filtered, function ($flight) use ($cabinClass) {
//                $travelerPricings = $flight['traveler_pricings'] ?? [];
//                if (empty($travelerPricings)) return true;
//
//                foreach ($travelerPricings as $pricing) {
//                    $flightCabin = strtoupper($pricing['cabin'] ?? 'ECONOMY');
//                    if ($flightCabin === $cabinClass) {
//                        return true;
//                    }
//                }
//
//                return false;
//            });
//        }
//
//        // 7. Duration Filter
//        if ($request->has('max_duration')) {
//            $maxDuration = (int)$request->input('max_duration');
//
//            $filtered = array_filter($filtered, function ($flight) use ($maxDuration) {
//                $duration = $flight['duration'] ?? '';
//                $durationMinutes = $this->parseDurationToMinutes($duration);
//                return $durationMinutes <= $maxDuration;
//            });
//        }
//
//        // 8. Sorting
//        if ($request->has('orderby')) {
//            $orderby = $request->input('orderby');
//
//            usort($filtered, function ($a, $b) use ($orderby) {
//                switch ($orderby) {
//                    case 'price_low_high':
//                        return ($a['price'] ?? 0) <=> ($b['price'] ?? 0);
//
//                    case 'price_high_low':
//                        return ($b['price'] ?? 0) <=> ($a['price'] ?? 0);
//
//                    case 'duration_low_high':
//                        $aDuration = $this->parseDurationToMinutes($a['duration'] ?? '');
//                        $bDuration = $this->parseDurationToMinutes($b['duration'] ?? '');
//                        return $aDuration <=> $bDuration;
//
//                    case 'duration_high_low':
//                        $aDuration = $this->parseDurationToMinutes($a['duration'] ?? '');
//                        $bDuration = $this->parseDurationToMinutes($b['duration'] ?? '');
//                        return $bDuration <=> $aDuration;
//
//                    case 'rate_high_low':
//                    case 'rating_high_low':
//                        return ($b['rating'] ?? 0) <=> ($a['rating'] ?? 0);
//
//                    case 'rate_low_high':
//                    case 'rating_low_high':
//                        return ($a['rating'] ?? 0) <=> ($b['rating'] ?? 0);
//
//                    default:
//                        return 0;
//                }
//            });
//        }
//
//
//        // Re-index array to remove gaps in keys
//        return array_values($filtered);
//    }

    /**
     * Check if time matches given time range
     */
    private function matchesTimeRange($timeString, $range)
    {
        if (empty($timeString)) return false;

        try {
            $time = \Carbon\Carbon::parse($timeString);
            $hour = $time->hour;

            // Parse range (e.g., "06-12")
            if (is_string($range)) {
                $range = [$range];
            }

            foreach ($range as $r) {
                [$start, $end] = explode('-', $r);
                $start = (int)$start;
                $end = (int)$end;

                if ($end === 0) $end = 24; // Handle 18-00

                if ($start < $end) {
                    // Normal range
                    if ($hour >= $start && $hour < $end) return true;
                } else {
                    // Overnight range
                    if ($hour >= $start || $hour < $end) return true;
                }
            }
        } catch (\Exception $e) {
            return false;
        }

        return false;
    }

    /**
     * Parse ISO 8601 duration to minutes
     */
    private function parseDurationToMinutes($duration)
    {
        if (empty($duration)) return 0;

        // Handle ISO 8601 format: PT2H30M
        if (preg_match('/PT(?:(\d+)H)?(?:(\d+)M)?/', $duration, $matches)) {
            $hours = isset($matches[1]) ? (int)$matches[1] : 0;
            $minutes = isset($matches[2]) ? (int)$matches[2] : 0;
            return ($hours * 60) + $minutes;
        }

        return 0;
    }

    /**
     * Get human-readable passenger type label
     *
     * @param string $code Passenger type code (ADT, C03, C07, CNN, INF, etc.)
     * @return string
     */
    private function getPassengerTypeLabel($code)
    {
        $labels = [
            'ADT' => 'Adult (12+ years)',
            'CNN' => 'Child (2-11 years)',
            'CHD' => 'Child (2-11 years)',
            'C02' => 'Child (2 years)',
            'C03' => 'Child (2-4 years, No UT3 tax)',
            'C04' => 'Child (4 years)',
            'C05' => 'Child (5 years)',
            'C06' => 'Child (6 years)',
            'C07' => 'Child (5-11 years, With UT3 tax)',
            'C08' => 'Child (8 years)',
            'C09' => 'Child (9 years)',
            'C10' => 'Child (10 years)',
            'C11' => 'Child (11 years)',
            'INF' => 'Infant (0-2 years)',
            'INS' => 'Infant (with seat)',
        ];

        return $labels[$code] ?? $code;
    }
}
